version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout

      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}

      - run:
          name: install python dependencies
          command: |
            pipenv install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
          paths:
            - ".venv"
      - run:
          name: run tests
          command: |
            pipenv run pytest --cov=./
            codecov
      - store_artifacts:
          path: htmlcov/
  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout

      - restore_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}

      - run:
          name: install python dependencies
          command: |
            pipenv install
            pip install --user --upgrade setuptools wheel
      - save_cache:
          key: v1-dependency-cache-{{ checksum "setup.py" }}
          paths:
            - ".venv"
      - run:
          name: verify git tag vs. version
          command: |
            pipenv shell
            python setup.py verify
      - run:
          name: init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = WeAreDevelopers" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: create packages
          command: |
            pipenv shell
            python setup.py sdist bdist_wheel
      - run:
          name: upload to pypi
          command: |
            pipenv shell
            twine upload dist/*
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
